import './globals.css'
import type { Metadata } from 'next'
import Header from './component/Header'
import Footar from './Footar/page'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pooja-Mittal - The Frontend developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
        <Header />
        {children}
      <Footar />
        </body>
    </html>
  )
}
